lab_name_dict = {'LAB1300': 'Recompte de leucòcits',
                  'LAB1301': 'Recompte plaquetes',
                  'LAB1307': 'Neutròfils absoluts (anal)',
                  'LAB1309': 'Limfòcits absoluts (analitzado',
                  'LAB1311': 'Monòcits absoluts (analitzador',
                  'LAB1313': 'Eosinòfils absoluts (analitzad',
                  'LAB1316': 'Basòfils absoluts (analitzador',
                  'LAB2404': 'Aspartat aminotransferasa (ASA',
                  'LAB2405': 'Alanin aminotransferasa (ALAT)',
                  'LAB2406': 'Gamma glutaril transferasa (GG',
                  'LAB2407': 'Bilirrubina total',
                  'LAB2419': 'Lactat deshidrogenasa (LDH)',
                  'LAB2422': 'Glucosa',
                  'LAB2467': 'Creatinina plasmàtica',
                  'LAB2469': 'Colesterol total',
                  'LAB2476': 'Triglicèrids',
                  'LAB2498': 'Proteïnes totals',
                  'LAB2544': 'Beta 2 microglobulina',
                  'LAB2679': 'Proteïna S100',
                  'LAB4176': 'Melanoma Inhibitory activity',
                  'LAB1314': 'Concentració dhemoglobina'}
